
export type AgentItems = {
  id: number,
  create_time: Date,
  sl_id: string,
  nik_name: string,
  wechat_id: string,
  sl_mask: string,
  is_search: number,
  ls_sex: string | "男" | "女",
  sl_intro: string,
  mask_open: string,
  type: string,
  owner: string,
  permission: number,
  owner_oepn: string,
  public: number,
  publish: number,
  human: number,
  mask_background: string,
  mask_open_degree: number,
  mask_character: string,
  mask_motivation: string,
  mask_reactive: string,
  mask_relationship: string,
  create_type: string,
  yuyan: string,
  fushi: string,
  zhuangtai: string,
  taidu: string,
  changsuo: string,
  mask_half: string,
  touxiang: string,
  p1: Date,
  p2: Date,
  p3: Date,
  p4: Date,
  myself: number,
  for_sex: string | "女性向" | "男性向"
  publish_sys: number,
  vip_level: number,
  room_slid: string,
  room_slname: string,
  free: string,
  voice_type: string,
  last_weibo: string
}