import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Whats Chat 创建属于你的女友",
  description: "Generated by create next app",
};

// 定义不需要显示 sidebar 和 SiteHead 的路由路径

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-cn" suppressHydrationWarning className="font-sans">
      <body className={`antialiased`}>
        <ThemeProvider defaultTheme="dark" attribute="class">
          {children}
          <Toaster position="top-center" expand={true} richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
